# common/supabase/schema_manager/supabase/service.py

class SupabaseService:
    def __init__(self, table, config_manager):
        self.table = table
        self.config_manager = config_manager
        self.file_name = self.config_manager.generate_file_name("service", self.table.camelCaseName)
        self.directory = self.config_manager.generate_directory_path("supabase")
        self.file_location_print = f"// File location: {self.directory}{self.file_name}"
        self.name = f"{self.table.PascalCaseName}Service"
        self.import_statement = f"import {{ {self.name} }} from '{self.directory}{self.file_name}';"

    def generate_service(self):
        return f"""// This file is generated by the schema manager
// {self.file_location_print}
import {{ supabase }} from '../../supabase';
import {{ {self.table.PascalCaseName} }} from '../models/{self.table.snakeCaseName}';
import {{ {self.table.PascalCaseName}Form }} from '../forms/{self.table.snakeCaseName}Form';
"""
