"""Backwards-compatibility shim for the historical pdf_handler module.

The PDF subsystem now lives in the ``pdf/`` subpackage (design §4.1). Every
public symbol that callers historically imported from this module is
re-exported here verbatim — no caller needs to update its import path.

For new code, prefer importing directly from the subpackage:

    from matrx_utils.file_handling.specific_handlers.pdf import PDFHandler
    from matrx_utils.file_handling.specific_handlers.pdf.ops import (
        extract_pages_from_bytes_async,
    )
"""

from __future__ import annotations

# Re-export everything the package's __init__.py exposes.
from .pdf import (  # noqa: F401
    ALL_PDF_PRESETS,
    LayoutClassificationReport,
    PageClass,
    PageClassification,
    ReadingOrderBlock,
    ReadingOrderPage,
    ReadingOrderReport,
    RegionKind,
    RepeatedRegion,
    RepeatedRegionBbox,
    RepeatedRegionsReport,
    classify_pages,
    classify_pages_async,
    classify_pages_stream,
    detect_repeated_regions,
    detect_repeated_regions_async,
    detect_repeated_regions_stream,
    extract_reading_order,
    extract_reading_order_async,
    extract_reading_order_stream,
    normalize_block_text,
    strip_repeated_regions_text,
    # Phase 4 redact
    BUILTIN_PATTERNS,
    RedactionAudit,
    RedactionRegion,
    RedactionResult,
    flatten_annotations,
    flatten_annotations_async,
    list_builtin_patterns,
    redact_pattern,
    redact_pattern_async,
    redact_regions,
    redact_regions_async,
    redact_repeated_regions,
    redact_repeated_regions_async,
    scrub_categories,
    scrub_categories_async,
    # Phase 2/3/4 wire schemas
    PdfRedactionPatternCatalog,
    PdfRedactionPatternEntry,
    PdfStudioBundleSchema,
    PdfStudioCatalog,
    PdfStudioCategorySchema,
    PdfStudioPresetSchema,
    PersistedPdfFile,
    PersistedRedactionResult,
    StripRepeatedRegionsResultSchema,
    strip_all_pii,
    strip_all_pii_async,
    strip_attachments,
    strip_attachments_async,
    strip_javascript,
    strip_javascript_async,
    strip_metadata,
    strip_metadata_async,
    PDF_PRESETS_BY_ID,
    PRESET_CATEGORIES,
    RECOMMENDED_PDF_BUNDLES,
    AiChunkProcessor,
    PDFHandler,
    PdfBinaryResult,
    PdfChunkedTextResult,
    PdfCropBox,
    PdfPageRange,
    PdfPageRender,
    PdfPageSpan,
    PdfPageText,
    PdfPipelineOptions,
    PdfRenderSpec,
    PdfResult,
    PdfSplitPart,
    PdfStudioBundle,
    PdfStudioCategory,
    PdfStudioPreset,
    PdfStudioRenderResult,
    PdfTextBlock,
    PdfTextChunk,
    PdfTextWord,
    build_info_payload,
    chunk_page_text,
    chunk_text,
    cleanup_tmp_older_than,
    compress_pdf_bytes,
    compress_pdf_bytes_async,
    crop_pages_in_bytes,
    crop_pages_in_bytes_async,
    delete_pages_from_bytes,
    delete_pages_from_bytes_async,
    duplicate_pages_in_bytes,
    duplicate_pages_in_bytes_async,
    extract_pages_from_bytes,
    extract_pages_from_bytes_async,
    extract_tables,
    extract_tables_async,
    extract_tables_structured,
    extract_tables_structured_async,
    extract_tables_structured_stream,
    PdfExtractedTable,
    PdfTableBbox,
    PdfTablesPageScanned,
    PdfTablesReport,
    extract_text_from_bytes_sync,
    extract_text_from_image_bytes,
    extract_text_from_pdf_bytes_sync,
    extract_text_pages,
    extract_text_pages_async,
    extract_text_pages_from_bytes,
    extract_text_pages_from_bytes_async,
    format_page_text,
    get_pdf_preset_by_id,
    insert_pages_in_bytes,
    insert_pages_in_bytes_async,
    install_startup_cleanup_hook,
    load_pymupdf,
    merge_pdfs_from_bytes,
    merge_pdfs_from_bytes_async,
    normalise_page_ranges,
    ocr_image_bytes,
    ocr_pymupdf_page,
    pdf_temp_dir,
    pdf_temp_file,
    process_chunks_with_ai,
    iter_render_pages_to_image_bytes,
    render_all_pages_to_image_bytes,
    render_all_pages_to_image_bytes_async,
    render_page_to_image_bytes,
    render_page_to_image_bytes_async,
    render_studio_variant,
    render_studio_variant_async,
    render_thumbnail_bytes,
    render_thumbnail_bytes_async,
    reorder_pages_in_bytes,
    reorder_pages_in_bytes_async,
    rotate_pages_in_bytes,
    rotate_pages_in_bytes_async,
    save_pymupdf_doc,
    split_pdf_bytes,
    split_pdf_bytes_async,
    write_pdf_bytes_to_temp,
)


__all__ = [
    "AiChunkProcessor",
    "PDFHandler",
    "PdfBinaryResult",
    "PdfChunkedTextResult",
    "PdfCropBox",
    "PdfPageRange",
    "PdfPageSpan",
    "PdfPageText",
    "PdfPipelineOptions",
    "PdfResult",
    "PdfSplitPart",
    "PdfTextBlock",
    "PdfTextChunk",
    "PdfTextWord",
    "extract_text_from_pdf_bytes_sync",
]
