# common/supabase/schema_manager/typescript/helpers.py
from common.supabase.schema_manager.technology_base import Technology

class TypeScriptHelper:
    def __init__(self, table, config_manager):
        self.table = table
        self.config_manager = config_manager
        self.file_name = self.config_manager.generate_file_name("typescript", self.table.camelCaseName)
        self.directory = self.config_manager.generate_directory_path("typescript")
        self.file_location_print = f"// File location: {self.directory}{self.file_name}"
        self.name = f"{self.table.PascalCaseName}Helper"
        self.import_statement = f"import {{ {self.name} }} from '{self.directory}{self.file_name}';"

    def generate_helper(self):
        return f"""// This file is generated by the schema manager
// {self.file_location_print}
import {{ {self.table.PascalCaseName} }} from '../models/{self.table.snakeCaseName}';
import {{ {self.table.PascalCaseName}Service }} from '../services/{self.table.snakeCaseName}Service';
import {{ {self.table.PascalCaseName}Form }} from '../forms/{self.table.snakeCaseName}Form';
"""
