from .asset_builder import (
    build_asset_from_master,
    image_dimensions,
    key_from_variant_record,
    sanitize_asset_metadata,
)
from .asset_envelope import (
    Asset,
    AssetCombinedOpResponse,
    AssetPatchRequest,
    AssetPdfCompressResponse,
    AssetPreviewRequest,
    AssetPreviewResponse,
    AssetPreviewVariant,
    AssetRenderMoreRequest,
    AssetUploadRequest,
    AssetVariant,
    BulkOperationResponse,
    BulkOperationResult,
    CopyInfo,
    FileRef,
    FocalPoint,
    PresetsResponse,
    PresetSummary,
    PresetVariantSummary,
    PreviewAnchor,
    PreviewFit,
    PreviewFormat,
    PreviewSource,
    PreviewVariantSpec,
    ShareLinkInfo,
    SubOpError,
    VisibilityLiteral,
)
from .backends import (
    BackendRouter,
    ParsedStorageUrl,
    S3Backend,
    ServerBackend,
    StorageBackend,
    SupabaseBackend,
    is_cloud_uri,
    is_storage_url,
    parse_storage_url,
    parse_uri,
)
from .base_handler import BaseHandler
from .batch_handler import BatchHandler
from .cloud_mixin import CloudMixin
from .cloud_sync import (
    CloudFile,
    CloudFilePermission,
    CloudFileVersion,
    CloudFolder,
    CloudGroupMember,
    CloudShareLink,
    CloudSyncConfig,
    CloudUserGroup,
    DatabaseClient,
    FileTreeEntry,
    PermissionsManager,
    configure_access_checker,
    SyncEngine,
    SyncResult,
    VersionManager,
    get_migration_sql,
    is_schema_applied,
    print_migration_sql,
    run_migrations,
)
from .dedup import (
    VALID_INTENTS,
    DedupDecision,
    DedupError,
    DedupLookupResult,
    DuplicateFileError,
    InvalidIntentError,
    MissingReasonError,
    UploadIntent,
    coerce_intent,
    compute_checksum,
    compute_checksum_stream,
    lookup_existing_async,
    resolve_dedup_policy,
    validate_force_new_copy_reason,
)
from .dedup import (
    resolve_async as resolve_dedup_async,
)
from .file_handler import FileHandler
from .file_manager import FileManager
from .local_files import open_any_file
from .media_sniff import (
    DANGEROUS_INLINE_MIMES,
    SNIFF_HEAD_BYTES,
    detect_av_track_kind,
    is_dangerous_inline_mime,
    sniff_mime_type,
)
from .service import FileService
from .specific_handlers.image_handler import (
    ALL_VARIANTS,
    AVATAR_VARIANTS,
    EMAIL_VARIANTS,
    FAVICON_VARIANTS,
    LOGO_VARIANTS,
    PODCAST_VARIANTS,
    PRESETS,
    SOCIAL_BASELINE,
    SOCIAL_VARIANTS,
    WEB_VARIANTS,
    ImageHandler,
    ImageVariant,
    PresetSpec,
    compose_preset,
    get_preset,
    list_preset_names,
)
from .specific_handlers.image_ops import (
    ASPECT_RATIO_PRESETS,
    OP_FAMILIES,
    OP_REGISTRY,
    BgRemoveParams,
    ImageOp,
    InpaintParams,
    OpParams,
    OpResult,
    compose_via_mask,
    detect_document_quad,
    inpaint_image,
    is_opencv_available,
    is_rembg_available,
    load_mask_from_png_bytes,
    remove_background,
)
from .specific_handlers.image_ops import (
    dispatch_op as dispatch_image_op,
)
from .specific_handlers.image_ops import (
    encode_image as encode_image_op_output,
)
from .specific_handlers.image_ops import (
    get_op as get_image_op,
)
from .specific_handlers.image_ops import (
    list_op_names as list_image_op_names,
)
from .specific_handlers.image_ops import (
    op_catalog as image_op_catalog,
)
from .specific_handlers.pdf_handler import (
    PdfBinaryResult,
    PdfChunkedTextResult,
    PdfCropBox,
    PDFHandler,
    PdfPageRange,
    PdfPageSpan,
    PdfPageText,
    PdfPipelineOptions,
    PdfResult,
    PdfSplitPart,
    PdfTextBlock,
    PdfTextChunk,
    PdfTextWord,
)
from .specific_handlers.video_compose import (
    FfmpegNotAvailableError,
    SlideSegment,
    compose_slideshow,
    compose_slideshow_async,
)
from .specific_handlers.video_handler import VideoHandler
from .system_paths import (
    AI_AUDIO,
    AI_DOCUMENTS,
    AI_IMAGES,
    AI_VIDEO,
    ANALYSIS_RESULTS,
    PAGE_RENDERS,
    PDF_DERIVATIVES,
    PDF_EXTRACTIONS,
    PDF_PAGE_PDFS,
    PREVIEWS,
    REDACTION,
    SCRAPER,
    THUMBNAILS,
    TRANSCRIPT_RECORDINGS,
    VARIANTS,
    SystemFolder,
    SystemPathRegistry,
    get_system_folder,
    is_system_path,
    list_system_folders,
    register_system_folder,
)

__all__ = [
    # Core
    "FileManager",
    "FileHandler",
    "FileService",
    # System path registry — canonical folders for automated saves
    "SystemFolder",
    "SystemPathRegistry",
    "register_system_folder",
    "get_system_folder",
    "list_system_folders",
    "is_system_path",
    "AI_IMAGES",
    "AI_AUDIO",
    "AI_VIDEO",
    "AI_DOCUMENTS",
    "VARIANTS",
    "THUMBNAILS",
    "PREVIEWS",
    "SCRAPER",
    "REDACTION",
    "ANALYSIS_RESULTS",
    "PAGE_RENDERS",
    "PDF_DERIVATIVES",
    "PDF_EXTRACTIONS",
    "PDF_PAGE_PDFS",
    "TRANSCRIPT_RECORDINGS",
    "build_asset_from_master",
    "sanitize_asset_metadata",
    "image_dimensions",
    "key_from_variant_record",
    "BatchHandler",
    "BaseHandler",
    "CloudMixin",
    "open_any_file",
    # MIME sniff (platform-level, used by every upload boundary)
    "DANGEROUS_INLINE_MIMES",
    "SNIFF_HEAD_BYTES",
    "detect_av_track_kind",
    "sniff_mime_type",
    "is_dangerous_inline_mime",
    # Asset envelope — canonical response shape for media uploads
    "VisibilityLiteral",
    "AssetVariant",
    "Asset",
    "FileRef",
    "AssetUploadRequest",
    "AssetPatchRequest",
    "AssetRenderMoreRequest",
    "SubOpError",
    "ShareLinkInfo",
    "CopyInfo",
    "AssetCombinedOpResponse",
    "FocalPoint",
    "PreviewAnchor",
    "PreviewFit",
    "PreviewFormat",
    "PreviewSource",
    "PreviewVariantSpec",
    "AssetPreviewRequest",
    "AssetPreviewVariant",
    "AssetPreviewResponse",
    "AssetPdfCompressResponse",
    "PresetVariantSummary",
    "PresetSummary",
    "PresetsResponse",
    "BulkOperationResult",
    "BulkOperationResponse",
    # Specialized handlers
    "ImageHandler",
    "VideoHandler",
    # Video composition (slideshow / sizzle-reel engine)
    "SlideSegment",
    "FfmpegNotAvailableError",
    "compose_slideshow",
    "compose_slideshow_async",
    "PDFHandler",
    "PdfBinaryResult",
    "PdfChunkedTextResult",
    "PdfCropBox",
    "PdfPageRange",
    "PdfPageSpan",
    "PdfPageText",
    "PdfPipelineOptions",
    "PdfResult",
    "PdfSplitPart",
    "PdfTextChunk",
    "PdfTextBlock",
    "PdfTextWord",
    # Image variant system
    "ImageVariant",
    "PODCAST_VARIANTS",
    "SOCIAL_VARIANTS",
    "WEB_VARIANTS",
    "EMAIL_VARIANTS",
    "LOGO_VARIANTS",
    "AVATAR_VARIANTS",
    "FAVICON_VARIANTS",
    "SOCIAL_BASELINE",
    "ALL_VARIANTS",
    "PresetSpec",
    "PRESETS",
    "get_preset",
    "compose_preset",
    "list_preset_names",
    # Cloud storage backends
    "StorageBackend",
    "S3Backend",
    "SupabaseBackend",
    "ServerBackend",
    "BackendRouter",
    "is_cloud_uri",
    "parse_uri",
    # URL parsing utilities
    "parse_storage_url",
    "is_storage_url",
    "ParsedStorageUrl",
    # Cloud sync
    "CloudSyncConfig",
    "SyncEngine",
    "SyncResult",
    "PermissionsManager",
    "configure_access_checker",
    "VersionManager",
    "DatabaseClient",
    "CloudFile",
    "CloudFolder",
    "CloudFileVersion",
    "CloudFilePermission",
    "CloudShareLink",
    "CloudUserGroup",
    "CloudGroupMember",
    "FileTreeEntry",
    "get_migration_sql",
    "run_migrations",
    "is_schema_applied",
    "print_migration_sql",
    # Content-hash dedup (strict-intent contract)
    "UploadIntent",
    "VALID_INTENTS",
    "DedupLookupResult",
    "DedupDecision",
    "DedupError",
    "DuplicateFileError",
    "InvalidIntentError",
    "MissingReasonError",
    "compute_checksum",
    "compute_checksum_stream",
    "coerce_intent",
    "validate_force_new_copy_reason",
    "lookup_existing_async",
    "resolve_dedup_policy",
    "resolve_dedup_async",
    # Image edit operations (registry + dispatcher + optional backends)
    "ASPECT_RATIO_PRESETS",
    "BgRemoveParams",
    "InpaintParams",
    "OP_FAMILIES",
    "OP_REGISTRY",
    "ImageOp",
    "OpParams",
    "OpResult",
    "compose_via_mask",
    "dispatch_image_op",
    "encode_image_op_output",
    "get_image_op",
    "detect_document_quad",
    "inpaint_image",
    "is_opencv_available",
    "is_rembg_available",
    "list_image_op_names",
    "load_mask_from_png_bytes",
    "image_op_catalog",
    "remove_background",
]
